CREATE TABLE IF NOT EXISTS clips
(id INTEGER PRIMARY KEY AUTOINCREMENT, clipname TEXT, streamname TEXT);

CREATE TABLE IF NOT EXISTS announcements
(id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT, content TEXT, posted DATETIME);