CREATE TABLE IF NOT EXISTS clips
(id INTEGER PRIMARY KEY AUTOINCREMENT, clipname TEXT, streamname TEXT, clipped DATETIME);

CREATE TABLE IF NOT EXISTS announcements
(id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT, content TEXT, posted DATETIME);

CREATE TABLE IF NOT EXISTS sounds
(id INTEGER PRIMARY KEY AUTOINCREMENT, soundname TEXT, library TEXT);
